# Generated by Django 5.0.6 on 2024-09-26 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0003_attendance_delete_blogmodel_delete_samplemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='attendance_images/'),
        ),
    ]
